_target_: gflownet.proxy.crystals.dav.DAV

release: v0-dev-embeddings
ckpt_path:
  mila: /network/scratch/s/schmidtv/Public/crystals/proxy-ckpts/v0-dev-embeddings
  victor: ~/Documents/Github/ActiveLearningMaterials/checkpoints/980065c0/checkpoints-3ff648a2
