_target_: gflownet.proxy.crystals.dav.DAV

release: v0-dev-embeddings
ckpt_path: /network/scratch/s/schmidtv/Public/crystals/proxy-ckpts/v0-dev-embeddings/epoch=12-step=11024-val_acc=0.23676522076129913.ckpt
