_target_: gflownet.proxy.crystals.dave.DAVE

release: v1.1-dev-embedding
ckpt_path:
  mila: /network/scratch/s/schmidtv/Public/crystals/proxy-ckpts/v1-dev-embedding
  victor: ~/Documents/Github/ActiveLearningMaterials/checkpoints/980065c0/checkpoints-3ff648a2
rescale_outputs: true
