[tool.poetry]
name = "gflownet"
version = "0.1.0"
description = "GFlowNets, generative flow networks for probabilistic modelling"
authors = ["Alex <alex.hernandez-garcia@mila.quebec>"]
readme = "README.md"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
hydra-core = ">=1.3.2"
pandas = ">=2.1.1"
plotly = ">=5.17.0"
pymatgen = ">=2023.9.25"
pyxtal = ">=0.6.0"
rdkit = "*"
scikit-learn = ">=1.3.1"
scipy = ">=1.11.2"
six = ">=1.16.0"
#torch = ">=2.0.1"
torch-geometric = ">=2.3.1"
torch-scatter = ">=2.1.1"
torchani = "*"
torchtyping = ">=0.1.4"
tqdm = "*"
wandb = ">=0.15.11"
# dglgo
# pip install dgl -f https://data.dgl.ai/wheels/repo.html
#gdown

# dev dependencies.
black = { version = ">=23.9.1", optional = true }
flake8 = { version = ">=6.1.0", optional = true }
isort = { version = ">=5.12.0", optional = true }
pylint = { version = ">=2.17.6", optional = true }
ipdb = { version = ">=0.13.13", optional = true }
jupyter = { version = ">=1.0.0", optional = true }
pytest = { version = ">=7.4.2", optional = true }
pytest-repeat = { version = ">=0.9.1", optional = true }

[tool.poetry.extras]
dev = [
    "black",
    "flake8",
    "isort",
    "pylint",
    "ipdb",
    "jupyter",
    "pytest",
    "pytest-repeat",
]