defaults:
  - base

_target_: gflownet.envs.crystals.clattice_parameters.CLatticeParameters

id: clattice_parameters

# Lattice system
lattice_system: triclinic
# Allowed ranges of size and angles
min_length: 1.0
max_length: 5.0
min_angle: 30.0
max_angle: 150.0

# Policy
beta_params_min: 0.01
beta_params_max: 1000.0
min_incr: 0.1
n_comp: 1
fixed_distribution:
  beta_weights: 1.0
  beta_alpha: 0.01
  beta_beta: 0.01
  bernoulli_source_logit: 0.0
  bernoulli_eos_logit: 0.0
random_distribution:
  beta_weights: 1.0
  # IMPORTANT: adjust because of sigmoid!
  beta_alpha: 0.01
  beta_beta: $beta_params_max
  bernoulli_source_logit: 0.0
  bernoulli_eos_logit: 0.0
# Buffer
buffer:
  data_path: null
  train: null
  test:
    type: grid
    n: 1000
    output_csv: ccube_test.csv
    output_pkl: ccube_test.pkl
