defaults:
  - base

_target_: gflownet.envs.ad_molecule_simple.ADMoleculeSimple

path_to_dataset: ${user.data.alanine_dipeptide}
id: ad_molecule_simple
policy_ecoding_dim_per_angle: null
# Fixed length of trajectories
length_traj: 10
# Parameters of the fixed policy output distribution
fixed_distribution:
  vonmises_mean: 0.0
  vonmises_concentration: 0.5
# Parameters of the random policy output distribution
random_distribution:
  vonmises_mean: 0.0
  vonmises_concentration: 0.001
# Buffer
buffer:
  data_path: null
  train: null
  test:
    type: grid
    n: 1000
    output_csv: ad_molecule_simple_test.csv
    output_pkl: ad_molecule_simple_test.pkl