defaults:
  - base

_target_: gflownet.envs.cube.ContinuousCube

id: ccube
continuous: True
func: corners
# Dimensions of hypercube
n_dim: 2
max_val: 1.0
# Policy
beta_params_min: 0.01
beta_params_max: 1000.0
min_incr: 0.1
n_comp: 1
fixed_distr_params:
  beta_params_min: ${beta_params_min}
  beta_params_max: ${beta_params_max}
  beta_weights: 1.0
  beta_alpha: 10.0
  beta_beta: 10.0
  bernoulli_bts_prob: 0.1
  bernoulli_eos_prob: 0.1
random_distr_params:
  beta_params_min: ${beta_params_min}
  beta_params_max: ${beta_params_max}
  beta_weights: 1.0
  beta_alpha: 1.0
  beta_beta: 1.0
  bernoulli_bts_prob: 0.1
  bernoulli_eos_prob: 0.1
# Buffer
buffer:
  data_path: null
  train: null
  test:
    type: grid
    n: 1000
    output_csv: ccube_test.csv
    output_pkl: ccube_test.pkl
