defaults:
  - base

_target_: gflownet.envs.cube.ContinuousCube

id: ccube
func: corners
# Dimensions of hypercube
n_dim: 2
max_val: 1.0
# Policy
beta_params_min: 0.1
beta_params_max: 2.0
min_incr: 0.1
n_comp: 1
fixed_distribution:
  beta_alpha: 2.0
  beta_beta: 5.0
random_distribution:
  beta_alpha: 1.0
  beta_beta: 1.0
# Buffer
buffer:
  data_path: null
  train: null
  test:
    type: grid
    n: 1000
    output_csv: ccube_test.csv
    output_pkl: ccube_test.pkl
