defaults:
  - base

_target_: gflownet.envs.crystals.Crystal

# Crystal parameters
id: crystal
max_diff_elem: 4
min_diff_elem: 2
periodic_table: 5
oxidation_states: 
  0: 
    - 1
    - -1
  1: 
    - -1
    - -2
  2: 
    - 2
  3: 
    - 2
  4: 
    - 3
    - 4
alphabet:
  0: H
  1: He
  2: Li
  3: Be
  4: B
min_atoms: 2
max_atoms: 20
min_atom_i: 1
max_atom_i: 10
# Buffer
buffer:
  data_path: null
  train:
    type: all
    output_csv: grid_train.csv
  test:
    type: all
    output_csv: grid_test.csv
