defaults:
  - base

_target_: gflownet.envs.crystals.Crystal

# Crystal parameters
id: crystal
max_diff_elem: 4
min_diff_elem: 2
elements: 5
min_atoms: 2
max_atoms: 20
min_atom_i: 1
max_atom_i: 10
# Buffer
buffer:
  data_path: null
  train:
    type: all
    output_csv: grid_train.csv
  test:
    type: all
    output_csv: grid_test.csv
