defaults:
  - base

_target_: gflownet.envs.htorus.HybridTorus

id: ctorus
func: sincos
# Dimensions of hypertorus
n_dim: 2
# Fixed length of trajectories
length_traj: 3
# Parameters of the fixed policy output distribution
vonmises_mean: 0.0
vonmises_concentration: 0.5
# Buffer
buffer:
  data_path: null
  train: null
  test:
    type: uniform
    n: 1000
    output_csv: ctorus_test.csv
