defaults:
  - base

_target_: gflownet.envs.plane.Plane

id: plane
func: corners
# Dimensions of hyperplane
n_dim: 2
# Maximum length of trajecotry
max_traj_length: 10
# Buffer
buffer:
  data_path: null
  train: null
  test:
    type: grid
    n: 1000
    output_csv: plane_test.csv
