defaults:
  - base

_target_: gflownet.envs.spacegroup.SpaceGroup

id: spacegroup
data:
  crystal_lattice_systems: ${user.data.root}/crystals/crystal_lattice_systems.yaml
  point_symmetries: ${user.data.root}/crystals/point_symmetries.yaml
  space_groups: ${user.data.root}/crystals/spacegroups.yaml

# Buffer
buffer:
  data_path: null
  train:
    type: all
    output_csv: spacegroup_train.csv
    output_pkl: spacegroup_train.pkl
  test:
    type: all
    output_csv: spacegroup_test.csv
    output_pkl: spacegroup_test.pkl
