defaults:
  - base

_target_: gflownet.envs.spacegroup.SpaceGroup

# Buffer
buffer:
  data_path: null
  train:
    type: all
    output_csv: spacegroup_train.csv
  test:
    type: all
    output_csv: spacegroup_test.csv
