defaults:
  - _self_
  - env: amp
  - env.buffer.train.path: /home/mila/n/nikita.saxena/activelearning/storage/amp/data_train.csv
  - gflownet: trajectorybalance
  - proxy: amp
  - logger: wandb
  - user: nikita

config.logger.project_name: "Scratch" 
config.env.amp.

gflownet.sample_only: False
gflownet.random_action_prob: 0.001
gflownet.optimizer.lr: 5e-4
gflownet.policy.forward.n_hid: 2048
gflownet.policy.forward.n_layers: 2
gflownet.pct_batch_empirical: 0.5
gflownet.n_train_steps: 10000

trajectorybalance.optimizer.lr: 5e-4
trajectorybalance.optimizer.lr_logZ: 1e-3 

# Number of objects to sample at the end of training
n_samples: 1000
# Random seeds
seed: 0
# Device
device: cuda

# Hydra config
hydra:
  # See: https://hydra.cc/docs/configure_hydra/workdir/
  run:
    dir: ${user.logdir.root}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    # See: https://hydra.cc/docs/upgrades/1.1_to_1.2/changes_to_job_working_dir/
    # See: https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/#disable-changing-current-working-dir-to-jobs-output-dir
    chdir: True

