_target_: gflownet.proxy.crystals.dave.DAVE

release: v3.1-physmlp-mbform
ckpt_path:
  mila: /network/scratch/s/schmidtv/crystals-proxys/proxy-ckpts/
  victor: ~/Documents/Github/ActiveLearningMaterials/checkpoints/980065c0/checkpoints-3ff648a2
rescale_outputs: true
