_target_: logger.Logger

do:
  online: False
  times: False

# Test metrics
test:
  period: 1
  n: 100
  kde:
    bandwidth: 0.1
    kernel: gaussian

# Log dir
logdir:
  root: ./logs
  ckpts: ckpts
  overwrite: True
lightweight: False 
progress: True
