name: Code Formatting and Tests

on: [push]

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3

      - name: Run Black on main source code
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./gflownet/"

      - name: Run Black on unit test code
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./tests/"

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install code dependencies
        run: pip install --upgrade https://github.com/alexhernandezgarcia/gflownet/archive/main.zip --quiet

      - name: Install Pytest
        run: pip install pytest

      - name: Validate import format
        uses: isort/isort-action@master

      - name: Run unit tests
        run: pytest